- Dockerfile
- docker-compose.yml
Created a Dockerfile for the webui and a docker-compose for the complete application including the scraper container.
"docker-compose up" should produce a working setup at port 5000
requires #15 to be merged
> Dockerfile for webui and docker-compose setup

- lookyloo/lookyloo.py
- website/web/__init__.py
- website/web/templates/scrape.html
> Add noindex button

- website/web/templates/tree.html
Allow to come back on base website from the tree view
> adding link to / on the logo in tree view

- .github/pull_request_template.md
Basic templates for Lookyloo repo to improve consistency and uniformity.
> Add Issues and PR templates to repo

- .github/issues_templates.md/bug_fix_template.md
- .github/issues_templates.md/documentation_change_template.md
- .github/issues_templates.md/new_feature_template.md
- .github/pull_request_template.md
Pull requests should be opened against the `main` branch. For more information on contributing to Lookyloo documentation, see the [Contributor Guidelines]().
* Add templates to repo 
* Adds templates to issues folder
> Issues templates

- .github/config.yml
Pull requests should be opened against the `main` branch. For more information on contributing to Lookyloo documentation, see the [Contributor Guidelines]().
**Description:** Adding contributor's guide
Fixes # n/a
* Adds an initial contributor's guide
* Details on using Git
* Basic styling doc or Asciidoc
> Initial set up for contributor's guide

- bin/update.py
Creating a correct hash for compute_hash_self()
> Generating correct hashes

- etc/systemd/system/lookyloo.service.sample
Add log to lookyloo when running with systemd
> add log to lookyloo's service

- lookyloo/lookyloo.py
> updating output for stats

- lookyloo/lookyloo.py
- website/web/__init__.py
- website/web/templates/stats.html
fixing typos and creating a stats page.
>  Fix typo and create a stats page

- website/web/templates/tree.html
A list item addition to tree.html for adding link to documentation and use cases
Fixes #142 
Adding a link to the menu for documentation.
*
*
*
> #142 Adding documentation link to the menu

- website/web/__init__.py
- website/web/templates/tree.html
Adding the final page title in the details of the tree.
> Adding the final page title in the details of the tree.

- README.md
Minor^minor update to the README, fix demo-URL.
> Update README.md - fix demo URL

- lookyloo/lookyloo.py
Solving the ""bug"" with tor-proxy when working in production (public)
> solving tor proxy for only_global_lookups

- lookyloo/lookyloo.py
- website/web/__init__.py
- website/web/templates/capture.html
- [ x] New feature *(non-breaking change which adds functionality)*
*
*
*
> Proxy field in capture page

- Dockerfile
Adding missing web deps to dockerfile ;)
> Installing missing web deps

- README.md
Table of Content links and LICENSE link in README.md were modified to be properly anchored with the correct root.
> Update README.md - Fix links

- lookyloo/lookyloo.py
- poetry.lock
- pyproject.toml
- website/web/__init__.py
- website/web/templates/hostname_popup.html
> Hostnode dl

- Dockerfile
- docker-compose.yml
**Description:** This PR aims to fix some Docker issues I encountered when trying to run the project with `docker-compose`.
Fixes #629 
* Add a container volume for logs
* Add LICENSE file to the container
* Update Playwright dependencies on the Docker image
> fixes for running lookyloo using docker-compose

- website/web/templates/misp_lookup.html
Changing the url to the MISP instance.
*
*
*
> Changed misp_url

- website/web/genericapi.py
Adding the possibility to get the response from the 3rd party modules.
- [x ] New feature *(non-breaking change which adds functionality)*
*
*
*
> Module response added

- lookyloo/lookyloo.py
- website/web/genericapi.py
Make send_email available from the API
*
*
*
> Made send_email available from the API

- lookyloo/modules/uwhois.py
> Remove redundant clause

- .github/workflows/instance_test.yml
Adding uwhoisd installation and configuration so that the tests can pass in the github actions.
*
*
*
> adding uwhoisd installation

- website/web/templates/tree_hashes_types.html
*
* the fix is simply to rename the ID so the datatables library knows which one it's supposed to update
*
> Fix: DataTable rename to treeHashesTable

- config/email.tmpl
- lookyloo/lookyloo.py
Adding a 3rd party module section to the email template. 
We want to display if an URL is malicious or not according to the 3rd party modules to provide more information.
*
*
*
> adding 3rd party report to mail

- config/generic.json.sample
- website/web/__init__.py
- website/web/sri.txt
- website/web/templates/capture.html
- website/web/templates/index.html
- website/web/templates/main.html
- website/web/templates/search.html
- website/web/templates/stats.html
- website/web/templates/tree.html
Adding the possibility to ignore the SRI values while developing (need to set "enable_ignore_sri" to true in the generic file).
*
*
*
> changes so that you can ignore the sri while developing

- website/web/templates/simple_capture.html
> fix: removing unnecessary script and jQuery

- lookyloo/lookyloo.py
- website/web/__init__.py
- website/web/sri.txt
- website/web/static/capture.js
- website/web/templates/capture.html
- website/web/templates/simple_capture.html
* admin-only auto-report checkbox at capture configuration: when it is checked a form is displayed where email, comment and recipient-email can be entered
* moving all scripts of capture.html to capture.js
* rewriting jQuery scripts of capture.js in vanilla JavaScript
*
> New: admin-only checkbox for auto-report

- cache/run_redis.sh
- indexing/run_redis.sh
- website/web/__init__.py
- website/web/templates/hashlookup.html
- website/web/templates/tree.html
Fixes bug #916 - accept hashlookup being disabled
Fixes #916
* cleanly show the message to the user instead of throwing an error in the code.
> fix: [modules] Gracefully accept no hashlookup fixes #916

- website/web/templates/tree.html
> Fixing typo

- website/web/genericapi.py
- [ x] New feature *(non-breaking change which adds functionality)*
*
*
*
> New: upload a capture via the API

- website/web/genericapi.py
Adding the possibility to get the uuids up to a certain timestamp
*
*
*
> Recent captures

- website/web/templates/index.html
Login message now always visible when logged in
*
*
*
> putting the login message in the right block

- lookyloo/lookyloo.py
- website/web/__init__.py
- website/web/sri.txt
- website/web/static/tree.css
- website/web/templates/macros.html
- website/web/templates/tree.html
Fixing the categorization and
adding a checklist to categorize quickly
- [x ] New feature *(non-breaking change which adds functionality)*
*
*
*
> Categories

- website/web/genericapi.py
Adding the possibility to get uuids by category via API.
If no category is specified, all categorized uuids will be returned
*
*
*
> new: get uuids by category via API

- website/web/genericapi.py
Add a new api endpoint to remove captures. 
Fixes #928
> add new endpoint to remove capture

- docker-compose.dev.yml
- docker-compose.yml
Adds modules subfolder to docker-compose.yml for development environment.
- [ X] New feature *(non-breaking change which adds functionality)*
- Updates docker-compose.yml to mount the modules folder to allow using docker as a development environment.
> Add modules folder to docker-compose.yml to allow live development

- website/web/genericapi.py
- new complex search endpoint for finding captures with multiple observables
- imports ipaddress library for ip address validation 
- validation functions for payloads
*
*
*
> New POST /json/advanced_search endpoint
